# Generated by Django 4.1.4 on 2023-06-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_created_by_order_updated_at_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='store.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='waitingapproval', max_length=50),
        ),
    ]
