# Generated by Django 4.1.4 on 2023-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
