# Generated by Django 4.1.4 on 2023-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_store_components_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store_components',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Store_components'},
        ),
    ]
